apiVersion: v2
name: cronus
description: proxying hyperscaler statless services
version: 0.1.16
dependencies:
  - name: rabbitmq
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.18.0
  - name: rabbitmq
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.18.0
    alias: rhea_rabbitmq
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.2.0
  - name: maillog
    repository: file://sub-charts/maillog
    version: 0.2.2
    condition: maillog.enabled
